finbourne/lusid-sdk-csharp-preview

- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Quotes.cs
Reverts finbourne/lusid-sdk-csharp-preview#16
> Revert "Develop.quotes"

- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Quotes.cs
This reverts commit 464afceda57888e307e8dfa172827257c74d04f5.
> Revert "Revert "Develop.quotes (#16)" (#17)"

- Dockerfile
- sdk/Lusid.Sdk/Model/MarketContextSuppliers.cs
- sdk/docs/AggregationApi.md
- sdk/docs/AnalyticsStoresApi.md
- sdk/docs/ApplicationMetadataApi.md
- sdk/docs/CorporateActionSourcesApi.md
- sdk/docs/CutLabelDefinitionsApi.md
- sdk/docs/DataTypesApi.md
- sdk/docs/DerivedTransactionPortfoliosApi.md
- sdk/docs/EntitiesApi.md
- sdk/docs/InstrumentsApi.md
- sdk/docs/LoginApi.md
- sdk/docs/MarketContextSuppliers.md
- sdk/docs/PortfolioGroupsApi.md
- sdk/docs/PortfoliosApi.md
- sdk/docs/PropertyDefinitionsApi.md
- sdk/docs/QuotesApi.md
- sdk/docs/ReconciliationsApi.md
- sdk/docs/ReferencePortfolioApi.md
- sdk/docs/ResultsApi.md
- sdk/docs/SchemasApi.md
- sdk/docs/ScopesApi.md
- sdk/docs/SearchApi.md
- sdk/docs/SystemConfigurationApi.md
- sdk/docs/TransactionPortfoliosApi.md
- sdk/runnings_tests.md
Look at the commits independently
> Update OpenAPI Generator 4.0.3

- Dockerfile
- docker-compose.yml
- sdk/Lusid.Sdk.Tests/Lusid.Sdk.Tests.csproj
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Instruments.cs
- sdk/Lusid.Sdk/Lusid.Sdk.csproj
Essentially remove it from the docker container setup so the build process picks up the one from the project
> Use generate.sh from project instead of docker container

- sdk/Lusid.Sdk.Tests/TokenProviderTests.cs
- sdk/Lusid.Sdk/Utilities/ApiConfigurationBuilder.cs
- sdk/Lusid.Sdk/Utilities/ClientCredentialsFlowTokenProvider.cs
- sdk/Lusid.Sdk/Utilities/LusidApiFactoryBuilder.cs
Reuses the auth token across multiple threads to avoid making unnecessary requests to Okta and hitting rate limits
> DEV-4681 Reuse auth token across multiple threads

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Portfolios.cs
Fix failing test after changes to ordering of properties on transactions
> DEV-4032: SDK test fix

- sdk/Lusid.Sdk.Tests/Utilities/DateTimeOrCutLabelTests.cs
- sdk/Lusid.Sdk/Utilities/DateTimeOrCutLabel.cs
> DEV-4597 Add Equals operator to DateTimeOrCutLabel

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Portfolios.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Instruments.cs
> TR-282: Fix API changes

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
Move from AnalyticStore to QuoteApi
> DEV-5134 Migrate to QuotesApi

- sdk/Lusid.Sdk.Tests/LusidApiTests.cs
> DEV-2045 Replaced use of header with body for schema links

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Holdings.cs
> DEV-1799 Added validation of ListHoldingsAdjustments

- sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
- sdk/Lusid.Sdk/Utilities/LusidApiFactoryBuilder.cs
- sdk/Lusid.Sdk/Utilities/TokenProviderConfiguration.cs
> Refactor creation of the LusidApiFactory to be threadsafe

- sdk/Lusid.Sdk/Utilities/TokenProviderConfiguration.cs
This reverts commit 36f74a6444bc6d8bb33184a181777acb09e57519.
> DEV-6405 Reapply "Revert change to access modifier"

- sdk/Dockerfile
- sdk/Lusid.Sdk.Tests/Lusid.Sdk.Tests.csproj
> DEV-6967 Upgrade tests to .Net Core 3.1

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
6760, but including the latest orderrequest properties change
> DEV-6760: update for properties array > dictionary change

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
Update tests to handle Side and OrderBook on Orders
> DEV-7212: add support for Side and OrderBook on Orders

- .travis.yml
- sdk/sonar-project.properties
> sonar setup

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
Fix tests to filter by scope where needed - and remember to run successful tests twice in contexts where state is important!
> DEV-7485: test correction

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
> Revert "DEV-7485: updated to handle new orders api"

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
This reverts (reapplies original) commit 85cd4e5d28ff6b6df6b2031c75f6e1c060879110.
Reapplication of previous PR.
> DEV-7485: updated to handle new orders api. Second attempt.

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
SDK change ok, but found performance problems in ListOrders server-side.
> DEV-7485: revert SDK update

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
Fix in LUSID.All now checks that we set properties properly ... this is a fix as a consequence.
> DEV-7848: fix, now that we're actually validating properties properly.

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Portfolios.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Reconciliation.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Instruments.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Quotes.cs
OpenApi3 has changed some param names and enum locations
> DEV-7749 Test Changes

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
scope is now required on creation of a configuration recipe in order that it can be stored and to align with requirements on list endpoints.
> DEV-8342 : addition of scope parameter to configuration recipe

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
> DEV-8335: Update sdk test with new aggregation endpoint

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
- sdk/Lusid.Sdk/Lusid.Sdk.csproj
- sdk/Lusid.Sdk/Utilities/ApiClient.Serialization.cs
- sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs
> DEV-8797 : solve deserialization of lusid instruments json converter problems

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
> Updating flow convention in c# sdk

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
> DEV-8692: updating index conventions following DTO change

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
> DEV-8908: update for removed resource supplier enum

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
> DEV-8937: Updated enum name for Fixed/Floating leg and added tests for remaining instruments

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
> DEV-9409: add creation demonstration for TermDeposit instruments

- sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
> DEV-9680: Fixed errorResonseDetails message

- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
(cherry picked from commit 4ccd9691a0d5515298ef7c575c379a10e1bb0dfa)
> DEV-8909: Valuation examples of instruments (#102)

- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
- strings deemed correct for API consistency/standards
> DEV-9890 : update SDK for migration of enums to strings

- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
> DEV-9890: Enum -> string for index day count convention

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InstrumentData.cs
> DEV-9890: Adding an example of swap creation using named conventions

- sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
Fix test to account for hex encoding
> SE-542 Account for hex encoding of value

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
> DEV-9088 : rebase test for the default holiday calendar becoming 'just weekends'

- sdk/Lusid.Sdk.Tests/Lusid.Sdk.Tests.csproj
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Bitemporal.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Holdings.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Portfolios.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Properties.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Reconciliation.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Transactions.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/CorporateActions.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Instruments.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Quotes.cs
- sdk/Lusid.Sdk.sln
- sdk/LusidFeatureReporter/LusidFeatureReporter.cs
- sdk/LusidFeatureReporter/LusidFeatureReporter.csproj
…view
Full attribute scanner scans the entire codebase for methods with [LusidFeature("code")] attributes and returns code values as a features.txt file inside the Sdk folder. All tests pass. Please review
> SE-303 LUSID feature reporter

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
> DEV-9972: Update test following deterministic pricer split

- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Instruments.cs
> DEV-10029: Assertion of no failures. Return/print failures, if any

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/ExampleMarketData/JPYOIS.json
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/ExampleMarketData/USD6M.json
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/ExampleMarketData/USDOIS.json
> DEV-10800: No longer supporting de/serialisation of ints to enums

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/ReferencePortfolioTests.cs
Port tests for features F39 and F40 to C# preview SDK from C# release SDK.
> SE-1045 Add feature tests to preview SDK from release SDK

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
> ANA-65:Changing DCC enum to string.

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
Reverts finbourne/lusid-sdk-csharp-preview#133
> Revert "ANA-65:Changing DCC enum to string."

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
Added an example that illustrates how to create a zero coupon bond and highlights the difference from creating a normal bond.
> ANA-135: Added example of creation of zero coupon bond.

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
> DEV-10668 : removing uses of aggregation from sdk

- sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
Update test for update LUSID error message
> SE-1121 Fix test for updated error message

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
- [ X ] Tests pass
- [ X ] Raised the PR against the `develop` branch
prop def for each prop in Orders tests
> PLAT-228: prop def for each prop on Orders

- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/PortfolioCashFlows.cs
> ANA-145: Adding sdk examples of getting fx forward cashflows

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/PortfolioCashFlows.cs
- [ Y ] Tests pass
- [ Y ] Raised the PR against the `develop` branch
Wrote an example of how to compute fixed rate bond cash flows.
> ANA-160: Sdk example on Bond cash flows.

- sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
- sdk/Lusid.Sdk.Tests/LusidApiTests.cs
- sdk/Lusid.Sdk.Tests/TokenProviderTests.cs
- sdk/Lusid.Sdk.Tests/Utilities/ApiConfigurationBuilderTest.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestLusidApiFactoryBuilder.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Bitemporal.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Holdings.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/PortfolioCashFlows.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Portfolios.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Properties.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Reconciliation.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/ReferencePortfolioTests.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Transactions.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InstrumentData.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/CorporateActions.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Instruments.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Quotes.cs
- sdk/Lusid.Sdk/Utilities/ApiConfiguration.cs
- sdk/Lusid.Sdk/Utilities/ApiConfigurationBuilder.cs
- sdk/Lusid.Sdk/Utilities/MissingConfigException.cs
- Secrets file is read if it exists
- Throws exception if secrets file does not exist
- If `null` secrets file, uses env variables
- Throws exception if any values are missing
> Tidy up the way that secrets/env variables are consumed

- sdk/Lusid.Sdk.Tests/LusidApiTests.cs
- sdk/Lusid.Sdk.Tests/TokenProviderTests.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestLusidApiFactoryBuilder.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Bitemporal.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Holdings.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Portfolios.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Properties.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Reconciliation.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/ReferencePortfolioTests.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Transactions.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InstrumentData.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/CorporateActions.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Instruments.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Quotes.cs
Typo in a previous PR that I did. `secret.json` needs to say `secrets.json` for tests to work with a local secrets file
> secret.json should be secrets.json

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Portfolios.cs
Update an out of date category annotation on one of the SDK tutorial for the list portfolio feature
> SE-1383: Updated tutorial category annotation

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/CutLabels.cs
The Label cleanup now deletes the specific set of test labels that were successfully created by the test, rather than trying to search through the list for the suffix.
> NOJIRA: Changed CutLabel deletion to delete the specific labels

- sdk/Lusid.Sdk/Lusid.Sdk.csproj
> Downgrade System.Component.Models to be the same version used elsewhere

- sdk/Lusid.Sdk/Lusid.Sdk.csproj
Reverts finbourne/lusid-sdk-csharp-preview#174
> Revert "Downgrade System.Component.Models to be the same version used elsewhere"

- sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/PortfolioCashFlows.cs
- sdk/Lusid.Sdk/Lusid.Sdk.csproj
- sdk/Lusid.Sdk/Utilities/ApiClient.Dispose.cs
- sdk/Lusid.Sdk/Utilities/ApiExceptionExtensions.cs
- sdk/Lusid.Sdk/Utilities/ApiResponseExtensions.cs
- sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs
Reverts finbourne/lusid-sdk-csharp-preview#173
> Revert "0.11.3308 manual changes"

- sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/PortfolioCashFlows.cs
- sdk/Lusid.Sdk/Lusid.Sdk.csproj
- sdk/Lusid.Sdk/Utilities/ApiClient.Dispose.cs
- sdk/Lusid.Sdk/Utilities/ApiExceptionExtensions.cs
- sdk/Lusid.Sdk/Utilities/ApiResponseExtensions.cs
- sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs
This reverts commit 693deacf67fa4bf4a5bc1005fcaff7261ae791fd.
> Revert "Open api manual changes take 2 (#180)"

- sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/PortfolioCashFlows.cs
- sdk/Lusid.Sdk/Lusid.Sdk.csproj
- sdk/Lusid.Sdk/Utilities/ApiClient.Dispose.cs
- sdk/Lusid.Sdk/Utilities/ApiExceptionExtensions.cs
- sdk/Lusid.Sdk/Utilities/ApiResponseExtensions.cs
- sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs
Reverts finbourne/lusid-sdk-csharp-preview#184
> Revert "Open api manual changes take 3"

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Properties.cs
Updated feature version in Properties.cs to new format
> SE-1709: Updated feature flag for Properties.cs

- sdk/Lusid.Sdk.Tests/TokenProviderTests.cs
- sdk/Lusid.Sdk/Utilities/ClientCredentialsFlowTokenProvider.cs
Reverts finbourne/lusid-sdk-csharp-preview#193
> Revert "invalid tokens now get new tokens, error messages result in 5 retries…"

- sdk/Lusid.Sdk.Tests/TokenProviderTests.cs
- sdk/Lusid.Sdk/Utilities/ClientCredentialsFlowTokenProvider.cs
> Se 1752 add retry capability when refresh token fails

- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/PortfolioCashFlows.cs
> ANA-463: Lifecycle management example of cashsettled equity option

- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/ExampleMarketData/XYZCorp.json
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapCashFlow.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapPricing.cs
Inserted unit tests for checking the CDS pricing and cashflows.
> ANA-687: Adding a CDS pricing and cash flow test example in Lusid.Sdk.

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapPricing.cs
- [Y] Read the [contributing guidelines](../blob/master/docs/CONTRIBUTING.md)
- [Y] Tests pass
- [Y] Raised the PR against the `develop` branch
> ANA-687: Missing Test attribute added in a test.

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
> ANA-796: MarketOption ctor fix

- sdk/Lusid.Sdk.Tests/Utilities/DemoInstrumentBase.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/Utilities/TutorialBase.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/PortfolioCashFlows.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/BondExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquityOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InstrumentData.cs
> ANA-688: Refactoring and renaming (no new functionality etc)

- sdk/Lusid.Sdk.Tests/Utilities/DemoInstrumentBase.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxOptionExamples.cs
> ANA-688: Resolve comments

- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/BondExamples.cs
I added an example how ZeroCouponBond can be created and used.
> ANA-686 add ZeroCouponBond example.

- sdk/Lusid.Sdk.Tests/Utilities/DemoInstrumentBase.cs
- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/BondExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquityOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ExoticExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FutureExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxFowardExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapWithNamedConventionsExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwaptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/TermDepositExamples.cs
> ANA-688: SimpleStatic pricing of various OTC instruments

- sdk/Lusid.Sdk.Tests/Utilities/TutorialBase.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapWithNamedConventionsExamples.cs
> ANA-688: Upsert conventions for named conventions swaps

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/PortfolioCashFlows.cs
Adds instrument scope parameter to transaction object.
> PLAT-650: Add instrument scope to transaction

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/PortfolioCashFlows.cs
> PLAT-650: Add instrument scope to transaction fix

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/PortfolioCashFlows.cs
> PLAT-650: Final fix to transaction object

- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ContractForDifferencesExamples.cs
SDK example for CFDs. Changes in Lusid already done.
> ANA-659: SDK example for CFD.

- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquityExample.cs
> Feature/seng 152.equityexampletests

- sdk/Lusid.Sdk.Tests/tutorials/MarketData/CorporateActions.cs
Added a corporate action example covering dividends, stock splits, and name changes. Tests include checks before and after each event as well as between ex-dates and payment dates for stock splits and dividends
> SE-1909: Added a CA example for dividend, stock split, and name change

- sdk/Lusid.Sdk.Tests/Lusid.Sdk.Tests.csproj
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapExamples.cs
- sdk/LusidFeatureReporter/LusidFeatureReporter.csproj
Fix duplicate feature in examples
> CTECH-654 fix duplicate feature

- sdk/Lusid.Sdk.Tests/Utilities/DemoInstrumentBase.cs
- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/Utilities/TutorialBase.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/BondExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ContractForDifferencesExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquityOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ExoticExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FutureExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxFowardExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapWithNamedConventionsExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwaptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/TermDepositExamples.cs
> ANA-891: Pricing swap example

- sdk/Lusid.Sdk.Tests/Utilities/DemoInstrumentBase.cs
- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/PortfolioCashFlows.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquityOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapWithNamedConventionsExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwaptionExamples.cs
> ANA-902: Refactoring existing Equity Option lifecycle test

- sdk/Lusid.Sdk.Tests/Utilities/DemoInstrumentBase.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/BondExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ContractForDifferencesExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquityOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FutureExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxFowardExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapWithNamedConventionsExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwaptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/TermDepositExamples.cs
> ANA-971: Swaption pricing example & ZCB pricing by SimpleStatic

- sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
> CTECH-714 unique quote per thread

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/BondExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ContractForDifferencesExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquityOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ExoticExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FutureExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxFowardExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapWithNamedConventionsExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwaptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/TermDepositExamples.cs
> CTECH-721 fix duplicate features

- sdk/Lusid.Sdk/Lusid.Sdk.csproj
Update RestSharp to resolve Dependabot security warning
> CTECH-719 update RestSharp 106.15.0

- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwaptionExamples.cs
> ANA-436: Swaption lifecycle

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquitySwapExamples.cs
> ANA-931: fix copy and pasting error

- sdk/Lusid.Sdk.Tests/Utilities/PollyApiRetryHandlerTests.cs
> SENG-54: potential test fix

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Bitemporal.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/CutLabels.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Holdings.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Portfolios.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Reconciliation.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/ReferencePortfolioTests.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Transactions.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Instruments.cs
- sdk/Lusid.Sdk.Tests/tutorials/MarketData/Quotes.cs
> migrated legacy labels of csharp-preview sdk to updated labels

- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquitySwapExamples.cs
> ANA-931: Lifecycle example for equity swap

- sdk/Lusid.Sdk.Tests/Utilities/DateTimeOrCutLabelTests.cs
- sdk/Lusid.Sdk/Utilities/DateTimeOrCutLabel.cs
Convert to UTC when creating cut labels
> CTECH-821 Fix utc times on cut labels

- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquitySwapExamples.cs
> ANA-1044: Valuation and cashflow for multicoupon equity swaps

- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapExamples.cs
> ANA-1117: Changing enum types to string for Instrument DTOs.

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
Make property definitions unque
> CTECH-891 fix orders examples

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Transactions.cs
Remove example superseded by instrument examples
> CTECH-1000 remove redundant example

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapExamples.cs
> ANA-910: Add example for InterestRateSwap lifecycle handling

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapExamples.cs
> ANA-910: Fix rebase conflict

- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapExamples.cs
…rs to avoid breaking SDK changes
> ANA-889: Name MarketDataType argument in ComplexMarketData constructors to avoid SDK breaking changes

- sdk/Lusid.Sdk.Tests/Utilities/DemoInstrumentBase.cs
- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/Utilities/TutorialBase.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/StructuredResultStore.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/BondExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ContractForDifferencesExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquityOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquitySwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxFowardExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapWithNamedConventionsExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwaptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwaptionWithNamedConventionsExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/TermDepositExamples.cs
> ANA-1315: Refactoring code

- sdk/Lusid.Sdk.Tests/Utilities/DemoInstrumentBase.cs
- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/StructuredResultStore.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/BondExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ContractForDifferencesExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquityExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquityOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquitySwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ExoticExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FutureExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxFowardExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxOptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InstrumentData.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapRfRExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapWithNamedConventionsExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwaptionExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwaptionWithNamedConventionsExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/TermDepositExamples.cs
> ANA-1190: Adding RFR/CAD Swap Examples

- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/ForwardRateAgreementExamples.cs
> ANA-1301: Add Creation and SimpleStatic valuation of FRAs

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/GenericReconciliation.cs
Added an example for each of the generic reconciliation rules.
> Feature/ana-1138 : Added examples of generic reconciliation matching rules.    

- sdk/Lusid.Sdk.Tests/tutorials/Instruments/EquityOptionExamples.cs
Demonstrate how to get option greeks out from a valuation call on equity options
> ANA-1145: demo the 6 supported equity option greeks

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/GenericReconciliation.cs
> ANA-1138: make tests orthogonal to Run_Valuation and tidy up

- sdk/Lusid.Sdk.Tests/Utilities/InstrumentExamples.cs
- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxForwardExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapFurtherExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapRfRExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapVanillaExamples.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/InterestRateSwapVariantExamples.cs
> ANA-1090: Cross-currency, basis, and amortising swap examples

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/FxForwardDiagnostics.cs
> ANA-54: Interpolation of fx forward rates from fx forward curve data

- sdk/Lusid.Sdk.Tests/tutorials/MarketData/MarketDataRules.cs
> ANA-993: Demo specific rules for quotes requested by options

- .github/workflows/build-and-test.yaml
temporarily increase build timeout
> CTECH-1360 update build timeout

- .github/workflows/build-and-test.yaml
> update build timeout

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/ReferencePortfolioTests.cs
> CTECH-1377 Fix SetConstituents race condition

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/StructuredResultStore.cs
- sdk/Lusid.Sdk.Tests/tutorials/Instruments/FxForwardExamples.cs
> ANA-566: Fix wrong tests

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/ReferencePortfolioTests.cs
> CTECH-1029 pipeline fix

- .github/workflows/build-and-test.yaml
Fixes the slack branch generation for the PR workflow.
> CTECH-1344: Fixes slack branch setting in workflow

- sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs
- [ x ] Read the [contributing guidelines](../blob/master/docs/CONTRIBUTING.md)
- [ x ] Tests pass
- [ x ] Raised the PR against the `develop` branch
> ANA-1527: allow cds to have negative pv

- sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
> DEV-12539: Add values for mandatory OrderRequest parameters in Orders tests

- sdk/Lusid.Sdk/Lusid.Sdk.csproj
Updated Newtonsoft from 12.0.3 to 13.0.1
> CTECH-1497 Bump Newtonsoft version in the SDK project

- sdk/docker-compose.yml
Signed-off-by: Paul Saunders <paul.saunders@finbourne.com>
uses the base url for the tests via the docker-compose file.  Tests have been run locally and pass.
> CTECH-1344: Fixes test run. Uses base url.

- sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
- sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs
- sdk/Lusid.Sdk/Utilities/LusidApiFactoryBuilder.cs
- sdk/docker-compose.yml
Adds optional parameter to set the `timeout` property on the `configuration`.
> CTECH-1502: Add timeout option via ApiFactory

- README.md
Added a reference to the new examples repo to the Readme
> CTECH-1151 Added a reference to the new examples repo into the readme

- sdk/Lusid.Sdk/Utilities/ApiResponseExtensions.cs
Make requestId header check case insensitive
> make requestId header check case insensitive

- sdk/Lusid.Sdk/Lusid.Sdk.csproj
It was noticed that the nuget link points back to the wrong repository. This PR fixes that.
> Fixes the repository link.
