sdk/Lusid.Sdk.Tests/tutorials/MarketData/Instruments.cs
Missing upper case I in attribute name. Tests won't pass as SDK has not been published yet.
=> Added missing upper case I

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
Adds first set of Orders tutorial integration tests.
=> DEV-6755: added Orders tutorial tests.

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs, sdk/Lusid.Sdk/Utilities/LusidApiFactoryBuilder.cs
Fixes threading issue in `LusidApiFactory` when used in an async context. The previous code assumed `ManagedThreadId` would be constant during an individual (single-threaded) request, but this is not the case if an async continuation (e.g. following an `await`) is employed in the calling application
=> DEV-6922: fix threading issue in LusidApiFactory

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
Accommodate upcoming Orders API changes:
- replace OrderId on outgoing DTO with ResourceId
- remove LusidInstrumentId from incoming DTO
- rename LusidInstrument as InstrumentUid on outgoing DTO
- (no longer require order properties)
=> DEV-6760: updated Orders tests

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
- Remove `Scope` from `Order`s routes.
- Order Id now a `ResourceId`
- Use `OrderId` `Scope` to determine scope of order.
- Enable filter on scope for orders and allocations.
- Ensure we write out `OrderId` as a safe string (no client) in logs.
- Corrects likely `UserId` > `Client.Name` problem in `SetEventHeader`.
- Re-organised some Orders tests.
=> DEV-7485: updated to handle new orders api

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
This reverts commit 68b2ba07a3eef16a1d0b285b7feac98ea0511941, reapplying this change.
Updating tests to handle removal of scope from routes, assorted other API changes.
=> DEV-7485: updated to handle new orders api.

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
Reapplies previous work to remove scope from Orders routes, and adds a set of performance improvements, specifically
- no longer querying for orders by scope group, and instead
- querying for orders by fully qualified id in a single fetch (if not paginated)
=> DEV-7485: remove scope from Orders routes

sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs, sdk/Lusid.Sdk.Tests/tutorials/Misc/ComplexInstruments.cs
The SDK generation creates various instruments using some of the newer polymorphic features in open swagger.
These test performs some verification that the SDK generation has not lost these.
=> DEV-8666: addition of swap, fx-forward instrument creation tests

.travis.yml
Temporarily disable sonar as there is a situation where SDK tests can fail but sonar passes resulting in travis thinking the build is successful. The sonar and sdk runs need to split into separate tasks
=> Disable sonar

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Properties.cs, sdk/Lusid.Sdk/Utilities/PropertyExtensions.cs
Properties now support multiple label values at a given effective time. Previously the value could be a single label or metric.
Initially multi-value properties are supported on portfolios only.
The corresponding Property Definition must have a ConstraintStyle of "Collection". Add multiple values using a PropertyValue containing a LabelValueSet.
=> DEV-8462: Support multi-value properties

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Transactions.cs, sdk/Lusid.Sdk.Tests/tutorials/Instruments/ComplexInstruments.cs, sdk/Lusid.Sdk.Tests/tutorials/MarketData/Instruments.cs
When initially added the lusid instrument model didn't exist for management of exotic instruments. As it now does, the upsert/delete/list end points for lusid instruments are now being migrated to the appropriate lusid instrument base class.
=> DEV-9094 : adjustments to local Sdk in migration of lusid instruments endpoints

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs
Changed the scope and code error messages according to the new messages that are going to be sent after DEV-9680 is merged on LUSID
=> DEV-9680: Prepared SDK error message tests for new ValidationAttributes

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk/Utilities/ApiExceptionExtensions.cs
The current implementation of GetRequestId throws an exception if the `ex.ErrorContent == null`. This merge request adds a null check before proceeding.
=> WEAL-1069: Guard against null reference exceptions when calling GetRequestId

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Orders.cs
`Order.OrderBookId` has recently been made optional. Ultimately, we'll remove it. In this PR, I remove it from SDK tests to demonstrate that it's optional, and to raise a flag if someone makes it a required field again.
=> DEV-11069: remove orderbookid from sdk tests

.github/workflows/build-and-test.yaml, sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk.Tests/TokenProviderTests.cs, sdk/Lusid.Sdk.Tests/Utilities/ApiConfigurationBuilderTest.cs, sdk/Lusid.Sdk.Tests/Utilities/ApiConfigurationTest.cs, sdk/Lusid.Sdk/Utilities/ApiConfiguration.cs, sdk/Lusid.Sdk/Utilities/ApiConfigurationBuilder.cs, sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs, sdk/Lusid.Sdk/Utilities/PersonalAccessTokenProvider.cs, sdk/docker-compose.yml
LUSID has support for Personal Access Tokens which can be used instead of acquiring Okta tokens though the OAuth or Authorisation flow
This is already supported by setting Configuration.AccessToken and passing to the LusidApiFactory(Configuration).
Added the ability to use the PAT (generated in LUSID) with the SDK and configured from env vars
Implemented a new PersonalAccessTokenProvider which implements ITokenProvider
Read the token from an env var set via FBN_ACCESS_TOKEN
Added PersonalAccessToken property to ApiConfiguration. If specified it takes precedence over the credentials 
Updated build pipeline with a PAT for both master and develop branches - stored as secrets and exposed via docker env variable. Values stored in LastPass for reference
=> SE-1215 added FBN_ACCESS_TOKEN implementation

sdk/Lusid.Sdk.Tests/tutorials/Ibor/Valuation.cs
Add test demonstrating inline valuation of a bond with different `DayCountConvention`s. This test demonstrates some of the different options available in terms of conventions and calendars when valuing a set of instruments.
=> ANA-340: Add test demonstrating inline valuation with different DayCountConventions and calendars

sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs, sdk/Lusid.Sdk.Tests/tutorials/Ibor/PortfolioCashFlows.cs
Adds a test demonstrating the lifecycle management of FxForwards. That is, the sum PV of the forward and its cashflows is constant over time (assuming constant FX rates and no discounting)
=> ANA-434: LifeCycle Management Of FxFwds

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk/Utilities/ApiExceptionExtensions.cs
Caused issues when 500s do not contain request ids
=> WEAL-2026: Fixup null reference exception when problem details does not contain request id

sdk/Lusid.Sdk.Tests/tutorials/Ibor/CutLabels.cs
The example currently uses times for a SNG close and LDN open which can overlap during daylight saving. This change moves the LDN open 1hr earlier so there is not an overlapping time with the cut labels
=> SE-1917 make example robust to daylight saving

sdk/Lusid.Sdk.Tests/tutorials/Instruments/CreditDefaultSwapCashFlow.cs
…mplexMarketDataAccessor.
ANA-729 will turn on functionality to filter ComplexMarketData based on the quoteInterval provided in MarketDataKeyRules given in the ConfigurationRecipe (see [this MR](https://gitlab.finbourne.com/finbourne/lusid/lusid-ibor/-/merge_requests/9054). Currently, quoteInterval does nothing in the complexMarketDataAccessor in Lusid, so we can safely change it on rules used for ComplexMarketData without making a functional change. This allows us to preemtively fix the tests that will break by turning on the filtering. This MR fixes the tests that will break in the C# SDK.
=> ANA-729: Specify QuoteInterval in rule for ComplexMarketData in preparation for switching on QuoteInterval Filtering

sdk/Lusid.Sdk.Tests/Utilities/ApiConfigurationBuilderTest.cs, sdk/Lusid.Sdk/Utilities/ApiConfigurationBuilder.cs
As a user, I'd like the sdk to fallback to env variables if the secrets file is invalid.
=> SE-1986 implemented

sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk.Tests/LusidExceptionHandlerTests.cs, sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs, sdk/Lusid.Sdk/Utilities/LusidExceptionHandler.cs
Under some circumstances we see SDK method calls returning null response values, which inevitably causes expected NullReferenceExceptions in calling code.
This PR makes the SDK throw an exception if the request fails to call the API at all (e.g. due to a network connectivity problem: bad URL / port etc), whereas it would previously return a null response.
=> PLAT-784: SDK should throw exceptions on network connectivity issues

sdk/Lusid.Sdk.Tests/Utilities/TestDataUtilities.cs, sdk/Lusid.Sdk.Tests/Utilities/TutorialBase.cs
- [ x ] Read the [contributing guidelines](../blob/master/docs/CONTRIBUTING.md)
- [ x ] Tests pass
- [ x ] Raised the PR against the `develop` branch
Market Data Key Rules allow one to specify where market data should be taken from when . For example, "ask TRKD for quotes", "check in scope 'myScope' for interest rates curves". These rules currently use the word "Equity" to refer to anything that can be looked up in the quotes store, including for example, a historical interest rate. This is confusing as it's not an equity. Now, we support the word "Quote" as an alias for "Equity", hopefully this new name is less confusing.
=> ANA-1214: rename Equity to Quote in  MarketDataRule keys

sdk/Lusid.Sdk.Tests/tutorials/Ibor/StructuredResultStore.cs
Upcoming changes in lusid will be disabling looking up UnitResult/Accrued in LusidPricingModel which in turn will cause the override to work in a different way than it did before. Clients are aware. This is an update for the notebook to match the lusid changes.
=> ANA-1476: Overriding of accrual no longer happens through UnitResult/Accrued, hence updating examples to reflect the changes.

.github/workflows/build-and-test.yaml, .gitignore, sdk/Dockerfile, sdk/Lusid.Sdk.Tests/Lusid.Sdk.Tests.csproj, sdk/Lusid.Sdk.Tests/LusidApiFactoryTests.cs, sdk/Lusid.Sdk.Tests/TokenProviderTests.cs, sdk/Lusid.Sdk.Tests/Utilities/ApiConfigurationBuilderTest.cs, sdk/Lusid.Sdk.Tests/Utilities/ApiConfigurationTests.cs, sdk/Lusid.Sdk/Utilities/ApiConfiguration.cs, sdk/Lusid.Sdk/Utilities/ApiConfigurationBuilder.cs, sdk/Lusid.Sdk/Utilities/LusidApiFactory.cs, sdk/Lusid.Sdk/Utilities/PersonalAccessTokenProvider.cs, sdk/docker-compose.yml
* Updates NUnit and the NUnit Test Adapter; this provides better support for
categorised tests among other niceties.
* Adds the token provider
* Give the PAT provider precedence over the ClientFlow Provider
* Adds tests
* Ensures tests that exclusively use the ClientFlow provider don't fail
if those secrets can't be found.
* Ensures tests the exclusively use the PAT provider don't fail if those
secrets can't be found.
* Tests that rely exclusively on one particular provider finish
Inconclusive if the secrets do not exist.  Other tests are unaffected
and will still require one or the other of the token providers to be
valid.
* Enables testing with a PAT in github actions by making changes to the 
Dockerfile and docker-compose files
=> Adds Personal Access Token Provider.

.github/workflows/notify-on-issue.yml, .github/workflows/slack-on-pr.yaml
When forked PR's are created, notifications are meant to be raised.  With the current setup, this is not possible.  This PR changes the workflow actions from `pull_request` to `pull_request_target`; `pull_request_target` runs in the context of the target branch, giving it access to secrets.  Because it is run on the target branch, the PR cannot exfiltrate any secrets or have changes to workflows run in the context of the target repository.  Reviewers still need to be vigilent of changes from unknown sources, especially around workflows.
=> Enables notifications for PR's and Issues on forked PR's

.github/workflows/notify-on-issue.yml, .github/workflows/slack-on-pr.yaml
When forked PR's are created, notifications are meant to be raised.  With the current setup, this is not possible.  This PR changes the workflow actions from `pull_request` to `pull_request_target`; `pull_request_target` runs in the context of the target branch, giving it access to secrets.  Because it is run on the target branch, the PR cannot exfiltrate any secrets or have changes to workflows run in the context of the target repository.  Reviewers still need to be vigilent of changes from unknown sources, especially around workflows.
=> CTECH-1344: Enables notifications for PR's and Issues on forked PR's

.github/workflows/build-and-test-branches.yaml, .github/workflows/build-and-test.yaml
Signed-off-by: Paul Saunders <pms1969@gmail.com>
This PR enables untrusted contributors to supply a fork based PR to the project.  Once reviewed by a trusted contributor (TC); that is a contributor who is a member of the organisation; the TC can comment on the PR with `/LGTM`, triggering a test run against a synthetic domain.
The mechanics of the trigger are fairly simple; an organisation level webhook fires to a webhook service that then triggers the workflow_dispatch resulting in the `build-and-test.yaml` action to fire, which creates a check_run so that the results of the testing are displayed prominently for all to see.
* `build-and-test-branches.yaml` now effectively only runs tests on a merge to the `develop` branch.
* `build-and-test.yaml` runs only for `workflow_dispatch` which is …
=> CTECH-1344: Enables PR Flow integration tests to be run with a /LGTM comment on the PR

sdk/Lusid.Sdk.Tests/tutorials/Ibor/StructuredResultStore.cs, sdk/docker-compose.yml
- adjustment to cashflow windowing. The movements engine maintains the 'exact' current worldview. Overriding of cashflows should therefore be with strict inequality looking forward as opposed to 'greater than equals' inequality. 
=> ANA-1599: adjustment to strict inequality on cashflow windowing/override
